<?php

declare(strict_types=1);

namespace SlimAPI\Tests\Integration\DI\Config\Adapters;

use SlimAPI\DI\Config\Adapters\NeonAdapter;
use SlimAPI\Tests\TestCase;

class NeonAdapterTest extends TestCase
{
    public function testLoad(): void
    {
        $adapter = new NeonAdapter();
        self::assertSame(
            'test_env_val',
            $adapter->load(__FIXTURES_DIR__ . '/neon_env_substitution.neon')['parameters']['specialParameter'],
        );
    }

    public function testDump(): void
    {
        $adapter = new NeonAdapter();
        $neon = <<<'EOT'
        # generated by Nette

        foo: bar

        EOT;

        self::assertSame($neon, $adapter->dump(['foo' => 'bar']));
    }
}
