<?php

declare(strict_types=1);

namespace SlimAPI\Tests\DI\Config\Adapters;

use SlimAPI\DI\Config\Adapters\NeonAdapter;
use SlimAPI\Tests\TestCase;

class NeonAdapterTest extends TestCase
{
    public function testLoad(): void
    {
        $adapter = new NeonAdapter();
        self::assertSame(['specialParameter' => 'foo'], $adapter->load(__DIR__ . '/config.neon')['parameters']);
    }

    public function testDump(): void
    {
        $adapter = new NeonAdapter();
        $neon = <<<'EOT'
        # generated by Nette

        foo: bar

        EOT;

        self::assertSame($neon, $adapter->dump(['foo' => 'bar']));
    }
}
